Get more info when contribution create fails
I just saw this in the failmail

Error: INVALID_MESSAGE Cannot create contribution, civi error!
Source: 'DB Error: unknown error'

There is not enough info to tell what it relates to so this patch increased the error info

Change-Id: I93ad1ced10a397e99fb87b8a5ce93e8ad5659e07