Revert "Process each message in a DB transaction"
This reverts commit 19f425b96193527f9a4834990ab490526d6de01a.

Error when deployed:
 Error: UNHANDLED ERROR. Halting Process. exception: SQLSTATE[HY000]: General
 error: 1205 Lock wait timeout exceeded; try restarting transaction

Conflicts:
	sites/all/modules/wmf_common/Queue.php

Change-Id: I9c6956f867c24238a6b6ad3fc8f70bf75b3c6bc9