Fix if grouping
This is resulting in a type error as organizationID is null but passed to a function that expects an int.

I think there is a mapping issue allowing it to get to this point, however, this reconfiguration of
the IF also makes sense

TypeError: Argument 1 passed to Civi\WMFHelper\Contact::isContactSoftCreditorOf() must be of the type int, null given, called in /srv/org.wikimedia.civicrm/drupal/sites/default/civicrm/extensions/wmf-civicrm/Civi/WMFHelper/Contact.php on line 204 in Civi\WMFHelper\Contact::isContactSoftCreditorOf() (line 121 of /srv/org.wikimedia.civicrm/drupal/sites/default/civicrm/extensions/wmf-civicrm/Civi/WMFHelper/Contact.php).

Bug: T377605
Change-Id: If37631db5c98ad5ebde26fc1a5b5b828bbaeb07e